---
language: java
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.m2"
env:
- TEST_MODULE=structr-core
- TEST_MODULE=structr-rest
- TEST_MODULE=structr-ui
script: mvn test -Dmaven.javadoc.skip=true -Dassembly.skipAssembly=true -DskipDeb=true
  -Denforcer.skip=true -pl $TEST_MODULE
